spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "3a!fB9vL@xD^PzQ7sK%tH8nM#jE4rT6wYpU2oI5dL0gZcVxNqF^mA8sK!dR4fB7Z"
  expiration: 3600000 # 1h
